package kirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.09.12 08:41:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaMainTest {
}