package kirjalista.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjalista.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.09.26 08:59:06 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AvainsanaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi50 */
  @Test
  public void testRekisteroi50() {    // Avainsana: 50
    Avainsana as1 = new Avainsana(); 
    assertEquals("From: Avainsana line: 52", 0, as1.getTunnusNro()); 
    as1.rekisteroi(); 
    Avainsana as2 = new Avainsana(); 
    as2.rekisteroi(); 
    int n1 = as1.getTunnusNro(); 
    int n2 = as2.getTunnusNro(); 
    assertEquals("From: Avainsana line: 58", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString88 */
  @Test
  public void testToString88() {    // Avainsana: 88
    Avainsana avs = new Avainsana(); 
    avs.uusiAvainsana(2,"Rikollisuus"); 
    avs.toString().equals("1|2|Rikollisuus"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse103 */
  @Test
  public void testParse103() {    // Avainsana: 103
    Avainsana avs = new Avainsana(); 
    String jono = "2|3|Murha"; 
    avs.parse(jono); 
    assertEquals("From: Avainsana line: 107", 3, avs.getKirjaNro()); 
    assertEquals("From: Avainsana line: 108", "Murha", avs.getAvainsana()); 
  } // Generated by ComTest END
}