package kirjalista.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import kirjalista.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.09.22 09:48:46 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AvainsanatTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoista100 
   * @throws SailoException when error
   */
  @Test
  public void testPoista100() throws SailoException {    // Avainsanat: 100
    Avainsanat avainsanat = new Avainsanat(); 
    Avainsana a1 = new Avainsana(); 
    Avainsana a2 = new Avainsana(); 
    Avainsana a3 = new Avainsana(); 
    avainsanat.lisaa(a1); avainsanat.lisaa(a2); 
    assertEquals("From: Avainsanat line: 108", false, avainsanat.poista(a3)); assertEquals("From: Avainsanat line: 108", 2, avainsanat.getLkm()); 
    assertEquals("From: Avainsanat line: 109", true, avainsanat.poista(a2)); assertEquals("From: Avainsanat line: 109", 1, avainsanat.getLkm()); 
  } // Generated by ComTest END
}