package kirjalista.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjalista.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.09.26 16:16:59 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** 
   * testClone40 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone40() throws CloneNotSupportedException {    // Kirja: 40
    Kirja kirja = new Kirja(); 
    kirja.parse("2|Valtio|Pratchett, Terry|2009|Haluan lukea|Suomi|324|1|2019-04-12|2019-10-12|"); 
    Kirja kopio = kirja.clone(); 
    Object olio = kirja.clone(); 
    assertEquals("From: Kirja line: 46", kirja.toString(), kopio.toString()); 
    kirja.parse("3|Valtio|Joku random|2009|Haluan lukea|Suomi|324|1|2019-04-12|2019-10-12|"); 
    assertEquals("From: Kirja line: 48", false, kopio.toString().equals(kirja.toString())); 
    assertEquals("From: Kirja line: 49", true, olio instanceof Kirja); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString76 */
  @Test
  public void testToString76() {    // Kirja: 76
    Kirja b1 = new Kirja(); 
    b1.setTunnusNro(3); 
    b1.aseta(1, "Valtio"); 
    b1.aseta(2, "Pratchett, Terry"); 
    b1.aseta(3, "5"); 
    b1.aseta(4, "2020-01-15"); 
    b1.aseta(5, "2020-02-19"); 
    b1.aseta(6, "2019"); 
    b1.aseta(7, "Kesken"); 
    b1.aseta(8, "Suomi"); 
    b1.aseta(9, "55"); 
    assertEquals("From: Kirja line: 88", "3|Valtio|Pratchett, Terry|2019|Kesken|Suomi|55|5|2020-01-15|2020-02-19|", b1.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse110 */
  @Test
  public void testParse110() {    // Kirja: 110
    Kirja b1 = new Kirja(); 
    b1.vastaaValtio(); 
    String jono = b1.toString(); ; 
    b1.parse(jono); 
    assertEquals("From: Kirja line: 115", "Valtio", b1.getNimi()); 
    assertEquals("From: Kirja line: 116", "Pratchett, Terry", b1.getKirjailija()); 
    assertEquals("From: Kirja line: 117", "Suomi", b1.getKieli());
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi151 */
  @Test
  public void testRekisteroi151() {    // Kirja: 151
    Kirja b1 = new Kirja(); 
    assertEquals("From: Kirja line: 153", 0, b1.getTunnusNro()); 
    b1.rekisteroi(); 
    Kirja b2 = new Kirja(); 
    b2.rekisteroi(); 
    int n1 = b1.getTunnusNro(); 
    int n2 = b2.getTunnusNro(); 
    assertEquals("From: Kirja line: 159", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi172 */
  @Test
  public void testGetNimi172() {    // Kirja: 172
    Kirja b1 = new Kirja(); 
    b1.vastaaValtio(); 
    { String _l_=b1.getNimi(),_r_="Valtio.*"; if ( !_l_.matches(_r_) ) fail("From: Kirja line: 175" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKirjailija186 */
  @Test
  public void testGetKirjailija186() {    // Kirja: 186
    Kirja b1 = new Kirja(); 
    b1.vastaaValtio(); 
    { String _l_=b1.getKirjailija(),_r_="Pratchett.*"; if ( !_l_.matches(_r_) ) fail("From: Kirja line: 189" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKieli212 */
  @Test
  public void testGetKieli212() {    // Kirja: 212
    Kirja b1 = new Kirja(); 
    b1.vastaaValtio(); 
    { String _l_=b1.getKieli(),_r_="Suomi.*"; if ( !_l_.matches(_r_) ) fail("From: Kirja line: 215" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}