package kirjalista.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;

import java.util.List;

import org.junit.*;
import kirjalista.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.09.26 16:32:09 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjalistaTest {



  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa37 
   * @throws SailoException when error
   */
  @Test
  public void testKorvaaTaiLisaa37() throws SailoException {    // Kirjalista: 37
    Kirjalista klista = new Kirjalista(); 
    Kirja b1 = new Kirja(); 
    b1.rekisteroi(); 
    klista.lisaa(b1); 
    assertEquals("From: Kirjalista line: 43", 1, klista.getKirjoja()); 
    Kirja b2 = new Kirja(); 
    b2.rekisteroi(); 
    klista.korvaaTaiLisaa(b2); 
    assertEquals("From: Kirjalista line: 47", 2, klista.getKirjoja()); 
    Kirja b3 = new Kirja(); 
    b3.rekisteroi(); 
    b3.setTunnusNro(b1.getTunnusNro()); 
    klista.korvaaTaiLisaa(b3); 
    assertEquals("From: Kirjalista line: 52", 2, klista.getKirjoja()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista65 
   * @throws Exception when error
   */
  @Test
  public void testPoista65() throws Exception {    // Kirjalista: 65
    Kirjalista klista = new Kirjalista(); 
    Kirja b1 = new Kirja(); 
    Kirja b2 = new Kirja(); 
    klista.lisaa(b1); klista.lisaa(b2); 
    assertEquals("From: Kirjalista line: 71", 2, klista.getKirjoja()); 
    klista.poista(b1); assertEquals("From: Kirjalista line: 72", 1, klista.getKirjoja()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista85 
   * @throws Exception when error
   */
  @Test
  public void testPoista85() throws Exception {    // Kirjalista: 85
    Kirjalista klista = new Kirjalista(); 
    Avainsana a1 = new Avainsana(); 
    a1.uusiAvainsana(1, "jee"); 
    klista.lisaa(a1); 
    List<Avainsana> avs = klista.annaAvainsanat(1); 
    assertEquals("From: Kirjalista line: 92", 1, klista.avainsanat.getLkm()); 
    klista.poista(a1); 
    avs = klista.annaAvainsanat(1); 
    assertEquals("From: Kirjalista line: 95", 0, klista.avainsanat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa108 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa108() throws SailoException {    // Kirjalista: 108
    Kirjalista kl = new Kirjalista(); 
    assertEquals("From: Kirjalista line: 111", 0, kl.getKirjoja()); 
    Kirja b1 = new Kirja(); 
    kl.lisaa(b1); 
    assertEquals("From: Kirjalista line: 114", 1, kl.getKirjoja()); 
  } // Generated by ComTest END
}