package kirjalista.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;

import java.util.List;

import org.junit.*;
import kirjalista.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.09.22 10:10:29 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjalistaTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoista48 
   * @throws Exception when error
   */
  @Test
  public void testPoista48() throws Exception {    // Kirjalista: 48
    Kirjalista klista = new Kirjalista(); 
    Kirja b1 = new Kirja(); 
    Kirja b2 = new Kirja(); 
    klista.lisaa(b1); klista.lisaa(b2); 
    assertEquals("From: Kirjalista line: 54", 2, klista.getKirjoja()); 
    klista.poista(b1); assertEquals("From: Kirjalista line: 55", 1, klista.getKirjoja()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista69 
   * @throws Exception when error
   */
  @Test
  public void testPoista69() throws Exception {    // Kirjalista: 69
    Kirjalista klista = new Kirjalista(); 
    Avainsana a1 = new Avainsana(); 
    a1.uusiAvainsana(1, "jee"); 
    klista.lisaa(a1); 
    List<Avainsana> avs = klista.annaAvainsanat(1); 
    assertEquals("From: Kirjalista line: 76", 1, klista.avainsanat.getLkm()); 
    klista.poista(a1); 
    avs = klista.annaAvainsanat(1); 
    assertEquals("From: Kirjalista line: 79", 0, klista.avainsanat.getLkm()); 
  } // Generated by ComTest END
}