package kirjalista.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjalista.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.09.12 08:55:52 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** 
   * testClone38 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone38() throws CloneNotSupportedException {    // Kirja: 38
    Kirja kirja = new Kirja(); 
    kirja.parse("2|Valtio|Pratchett, Terry|2009|Haluan lukea|Suomi|324|1|2019-04-12|2019-10-12|"); 
    Kirja kopio = kirja.clone(); 
    Object olio = kirja.clone(); 
    assertEquals("From: Kirja line: 44", kirja.toString(), kopio.toString()); 
    kirja.parse("3|Valtio|Joku random|2009|Haluan lukea|Suomi|324|1|2019-04-12|2019-10-12|"); 
    assertEquals("From: Kirja line: 46", false, kopio.toString().equals(kirja.toString())); 
    assertEquals("From: Kirja line: 47", true, olio instanceof Kirja); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString74 */
  @Test
  public void testToString74() {    // Kirja: 74
    Kirja b1 = new Kirja(); 
    b1.setTunnusNro(3); 
    b1.aseta(1, "Valtio"); 
    b1.aseta(2, "Pratchett, Terry"); 
    b1.aseta(3, "5"); 
    b1.aseta(4, "2020-01-15"); 
    b1.aseta(5, "2020-02-19"); 
    b1.aseta(6, "2019"); 
    b1.aseta(7, "Kesken"); 
    b1.aseta(8, "Suomi"); 
    b1.aseta(9, "55"); 
    assertEquals("From: Kirja line: 86", "3|Valtio|Pratchett, Terry|2019|Kesken|Suomi|55|5|2020-01-15|2020-02-19|", b1.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi139 */
  @Test
  public void testRekisteroi139() {    // Kirja: 139
    Kirja b1 = new Kirja(); 
    assertEquals("From: Kirja line: 141", 0, b1.getTunnusNro()); 
    b1.rekisteroi(); 
    Kirja b2 = new Kirja(); 
    b2.rekisteroi(); 
    int n1 = b1.getTunnusNro(); 
    int n2 = b2.getTunnusNro(); 
    assertEquals("From: Kirja line: 147", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi160 */
  @Test
  public void testGetNimi160() {    // Kirja: 160
    Kirja b1 = new Kirja(); 
    b1.vastaaValtio(); 
    { String _l_=b1.getNimi(),_r_="Valtio.*"; if ( !_l_.matches(_r_) ) fail("From: Kirja line: 163" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKirjailija174 */
  @Test
  public void testGetKirjailija174() {    // Kirja: 174
    Kirja b1 = new Kirja(); 
    b1.vastaaValtio(); 
    { String _l_=b1.getKirjailija(),_r_="Pratchett.*"; if ( !_l_.matches(_r_) ) fail("From: Kirja line: 177" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKieli200 */
  @Test
  public void testGetKieli200() {    // Kirja: 200
    Kirja b1 = new Kirja(); 
    b1.vastaaValtio(); 
    { String _l_=b1.getKieli(),_r_="Suomi.*"; if ( !_l_.matches(_r_) ) fail("From: Kirja line: 203" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}